/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "main.h"
#include <stdio.h>

#define MindxPassBand 3 //minimum differential value for the filter
#define MaxdxPassBand 100//Maximum differential value for the filter

I2C_HandleTypeDef hi2c1;
UART_HandleTypeDef huart1;

void Clock_Config(void);
static void GPIO_Init(void);
static void I2C_Init(void);
static void UART_Init(void);

static const uint8_t AXS_ADDR = 0x53 << 1; //predefined adress for ADXL345

void StartADXL(void);
void ReadADXL (void);
int overlapse_filter (int x);
int PassBandFilter(int xx, int pxx);

char aa[26];
uint8_t buf[6];

int xx, yy , zz;
uint16_t x, y , z;

int main(void)
{
  HAL_Init();
  Clock_Config();
  GPIO_Init();
  I2C_Init();
  UART_Init();

  int pxx, pyy , pzz;

  //START ADXL345 accelerometer
  StartADXL();

  ReadADXL();
  pxx = xx;
  pyy = yy;
  pzz = zz;

  while (1)
  {
    ReadADXL ();
    xx = PassBandFilter(xx, pxx);
    yy = PassBandFilter(yy, pyy);
    zz = PassBandFilter(zz, pzz);

    sprintf((char*)aa, "%03d,%03d,%03d\r\n", xx-pxx, yy-pyy, zz-pzz);
    HAL_UART_Transmit(&huart1, (unsigned char*)aa, 20, 20);

    pxx = xx;
    pyy = yy;
    pzz = zz;
  }
}

void StartADXL(void)
{
  //reset
  uint8_t data[2];
  data [0] = 0X00;
  data [1] = 0X01;
  HAL_I2C_Master_Transmit(&hi2c1, AXS_ADDR, data, 2, 10);
  //REG_POWERCTRL reset
  data [0] = 0X2d;
  data [1] = 0X00;
  HAL_I2C_Master_Transmit(&hi2c1, AXS_ADDR, data, 2, 10);
  //REG_POWERCTRL start at x variable
  data [0] = 0X2d;
  data [1] = 0X08;
  HAL_I2C_Master_Transmit(&hi2c1, AXS_ADDR, data, 2, 10);
  //+- 4G RANGE
  data [0] = 0X31;
  data [1] = 0X01;
  HAL_I2C_Master_Transmit(&hi2c1, AXS_ADDR, data, 2, 10);
}

int PassBandFilter(int xx, int pxx)
{
  int dx = xx-pxx;// first order derivative of the signal
  if(dx < 0) dx = dx*(int)-1; // absolute value of dx
  if (dx > MaxdxPassBand || dx < MindxPassBand) xx = pxx;// Limits of the filter
  return xx;
}

void ReadADXL (void)
{
  HAL_I2C_Mem_Read(&hi2c1, AXS_ADDR, 0X32, 1, buf, 6, 100);
  x = (buf[1]>>8)| buf[0];
  y = (buf[3]>>8)| buf[2];
  z = (buf[5]>>8)| buf[4];
  xx = x;
  yy = y;
  zz = z;
}

void Clock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI_DIV2;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL2;
  HAL_RCC_OscConfig(&RCC_OscInitStruct);

  RCC_ClkInitStruct.ClockType =
  RCC_CLOCKTYPE_HCLK|
  RCC_CLOCKTYPE_SYSCLK|
  RCC_CLOCKTYPE_PCLK1|
  RCC_CLOCKTYPE_PCLK2;

  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
  HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0);
}

static void I2C_Init(void)
{
  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  HAL_I2C_Init(&hi2c1);
}

static void UART_Init(void)
{
  huart1.Instance = USART1;
  huart1.Init.BaudRate = 9600;
  huart1.Init.WordLength = UART_WORDLENGTH_8B;
  huart1.Init.StopBits = UART_STOPBITS_1;
  huart1.Init.Parity = UART_PARITY_NONE;
  huart1.Init.Mode = UART_MODE_TX;
  huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart1.Init.OverSampling = UART_OVERSAMPLING_16;
  HAL_UART_Init(&huart1);
}

static void GPIO_Init(void)
{
  __HAL_RCC_GPIOD_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
}
